config/routes.rb
Rails.application.routes.draw do

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

  get 'dashboard/index'

  scope "/admin" do
    get '/', to: 'dashboard#index'
  end

  scope ':locale', locale: /en|fr/ do
    root 'home#land'
    devise_for :users, :path => 'accounts'
    resources :data
    resources :users
    resources :profiles
    post 'profiles/load', :to => 'profiles#load'

    resources :trails do
      resources :events do
        resources :event_registrations
      end
    end

    resources :posts

    get "/:id" => "high_voltage/pages#show", :as => :page, :format => false
  end
  
end

app/models/home.rb
class Home
  def next_trail
    next_trail ||= Trail.includes(:events).where('date >= ? AND location = ?', DateTime.now, 'Rodrigues').order(date: :asc).first
  end

  def next_trail_events
    next_trail.events
  end

  def sponsors
    Dir.glob("app/assets/images/sponsors/*.jpg")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :disable_nav, only: [:land]

  def land
    @home = Home.new
  end

private
  def disable_nav
    @disable_nav = true
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/land.html.erb
<div class="tile tile-lg tile-pink">
  <span class="content-wrapper">
    <span class="tile-content">
      <span class="tile-img tile-img-bg load-first beach-start"></span>
      <span class="tile-holder tile-holder-sm">
        <span class="title">
          <%= t('trail_of_rodrigues.title') %>
        </span>
      </span>
    </span>      
  </span>
</div>

<div class="tile tile-lg tile-narrow tile-deep-orange">
  <span class="content-wrapper">
    <%= image_tag 'tdr-logo.jpg', alt: "Trail of Rodrigues Logo", width: '100%', class: 'load-first' %>
    <span class="tile-content half-height">
      <h2>
        <%= t('trail_of_rodrigues.title') %>
      </h2>
      <h4>
        <%= t('trail_of_rodrigues.strapline') %>
      </h4>
      <p>
        <%= t('trail_of_rodrigues.date') %>
      </p>
      <p class="tile-footer">
        <%= link_to "https://www.facebook.com/TrailDeRodrigues", class: 'btn-floating btn-large waves-effect waves-light social-icon', target: '_blank' do %>
          <%= image_tag 'facebook_icon_56.png', alt: "Facebook Icon", class: 'load-first' %>
        <% end %>
        <%= link_to raw("<i class='material-icons'>arrow_forward</i>"), page_path('trail-rodrigues'), class: "btn-floating btn-large waves-effect waves-light orange" %>
      </p>
    </span>      
  </span>
</div>

<div class="tile tile-lg tile-narrow tile-green">
  <span class="content-wrapper">
    <%= image_tag 'logo-rod-trail-medium.jpg', alt: "Rod Trail Association image", width: '100%', class: 'load-first' %>
    <span class="tile-content half-height">
      <%= t('rta.about_home_page_html') %>
      <p class="tile-footer">
        <%= link_to "https://www.facebook.com/Rod-Trail-Association-619082944875069", class: 'btn-floating btn-large waves-effect waves-light social-icon', target: '_blank' do %>
          <%= image_tag 'facebook_icon_56.png', alt: "Facebook Icon", class: 'load-first' %>
        <% end %>
        <%= link_to raw("<i class='material-icons'>arrow_forward</i>"), page_path('rod-trail-association'), class: "btn-floating btn-large waves-effect waves-light green" %>
      </p>
    </span>      
  </span>
</div>

<%= link_to page_path('rodrigues'), class: "tile tile-lg tile-cyan ripple-effect" do %>
  <span class="content-wrapper">
    <span class="tile-content">
      <span class="tile-img tile-img-bg band"></span>
      <span class="tile-holder tile-holder-sm">
        <span class="title">
          <%= t('rodrigues.discover_title') %> <i class="material-icons">arrow_forward</i>
        </span>
      </span>
    </span>
  </span>
<% end %>

<div class="tile tile-lg tile-light-blue">
  <span class="content-wrapper">
    <span class="tile-content">
      <span class="tile-img tile-img-bg mountain-goat"></span>
    </span>      
  </span>
</div>

<div class="tile tile-lg tile-narrow tile-shorten tile-cyan ripple-effect">
  <span class="content-wrapper">
    <span class="tile-content">
      <h2>
        <%= t('trail_league.title') %>
      </h2>
      <p>
        <%= t('trail_league.about') %>
      </p>
      <% if @home.next_trail %>
        <h4>
          <%= t('trail_league.next_trail') %>
        </h4>
        <span class="title">
          <h3 class="next-trail-name">
            <%= link_to raw("#{@home.next_trail.name} <i class='material-icons'>arrow_forward</i>"), trail_path(@home.next_trail) %>
          </h3>
       </span>

        <%= l @home.next_trail.date, format: '%-d %B %Y' if @home.next_trail.date %>
        <p class="tile-footer">
          <%= link_to raw("<i class='material-icons'>arrow_forward</i>"), trails_path, class: "btn-floating btn-large waves-effect waves-light blue" %>
        </p>
      <% end %>
    </span>      
  </span>
</div>

<%= render "common/testimonial" %>

<%= render "common/sponsors" %>