config/routes.rb
Rails.application.routes.draw do

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

  get 'dashboard/index'

  scope "/admin" do
    get '/', to: 'dashboard#index'
  end

  scope ':locale', locale: /en|fr/ do
    root 'home#land'
    devise_for :users, :path => 'accounts'
    resources :data
    resources :users
    resources :profiles
    post 'profiles/load', :to => 'profiles#load'

    resources :trails do
      resources :events do
        resources :event_registrations
      end
    end

    resources :posts

    get "/:id" => "high_voltage/pages#show", :as => :page, :format => false
  end
  
end

app/models/event_registration.rb
# == Schema Information
#
# Table name: event_registrations
#
#  id             :integer          not null, primary key
#  event_id       :integer
#  profile_id     :integer
#  paid           :boolean
#  amount         :decimal(, )
#  currency       :string
#  payment_date   :datetime
#  payment_method :string
#  transaction_id :string
#  race_number    :integer
#  race_category  :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class EventRegistration < ActiveRecord::Base
  belongs_to :event
  belongs_to :profile

  validates :event_id, :profile_id, presence: true

  validate :cannot_register_more_than_once_per_trail

  comma do
    event :distance
    profile :first_name             
    profile :family_name            
    profile :date_of_birth        
    profile :email                  
    profile :mobile                 
    profile :gender                 
    profile :nationality            
    profile :country_of_residence   
    profile :passport_number        
    profile :tshirt_size            
    profile :emergency_contact_name 
    profile :emergency_contact_phone
    paid
  end

private
  def cannot_register_more_than_once_per_trail
    related_events = self.event.related_events.map(&:id)
    errors.add(:event_id, "is duplicate") if EventRegistration.find_by(event_id: related_events, profile_id: profile_id)
  end
end

app/controllers/event_registrations_controller.rb
# == Schema Information
#
# Table name: event_registrations
#
#  id             :integer          not null, primary key
#  event_id       :integer
#  profile_id     :integer
#  paid           :boolean
#  amount         :decimal(, )
#  currency       :string
#  payment_date   :datetime
#  payment_method :string
#  transaction_id :string
#  race_number    :integer
#  race_category  :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class EventRegistrationsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]

  def index
    event = Event.includes(:trail).find(params[:event_id])
    render csv: EventRegistration.where("event_id = ?", params[:event_id]), filename: "#{event.trail.name}_#{event.distance}k_registrations_#{Time.now.strftime('%d-%m-%Y_%H:%M:%S')}"
  end

  def new
    @event = Event.includes(:trail).find(params[:event_id])
    if current_user.is_admin?
      @registrations = @event.registrations.includes(:profile).all
      @registration = EventRegistration.new
      @trailers = Profile.all
      @profile = Profile.new
    end
  end

  def create
    @admin = current_user.is_admin?
    @event = Event.find(params[:event_id])
    if @admin
      @registration = EventRegistration.new(registration_params)
      # @registration.paid = (@registration.amount > 0)
      @registration.payment_date = Time.now
      @registration.event = @event
      @registration.save
    else
      trailer = current_user.profile
      @event.register(trailer)
      @trail = @event.trail
      @trail.events.each do |event|
        if current_user.profile.is_registered?(event)
          @registered_event = event
        end
      end
    end
  end

  def destroy
    @registration = EventRegistration.find(params[:id])
    @registration.destroy
  end

private
  def registration_params
    params.require(:event_registration).permit(:amount, :currency, :payment_method, :race_category, :profile_id)
  end

end

app/helpers/event_registrations_helper.rb
# == Schema Information
#
# Table name: event_registrations
#
#  id             :integer          not null, primary key
#  event_id       :integer
#  profile_id     :integer
#  paid           :boolean
#  amount         :decimal(, )
#  currency       :string
#  payment_date   :datetime
#  payment_method :string
#  transaction_id :string
#  race_number    :integer
#  race_category  :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

module EventRegistrationsHelper
end

app/views/event_registrations/_event_registration.html.erb
<tr id="<%= dom_id(event_registration) %>">
  <td><%= event_registration.profile.full_name %></td>
  <td><%= event_registration.race_category %></td>
  <td><%= event_registration.amount %></td>
  <td><%= link_to raw("<i class='material-icons'>remove_circle</i>"), trail_event_event_registration_path(@event.trail, @event, event_registration), method: :delete, remote: true %></td>
</tr>

app/views/event_registrations/_form.html.erb
<div id="registration-form" class="card-panel">
<h3>
  Register trailers for this event
</h3>
<%= simple_form_for [@event.trail, @event, @registration], remote: true do |f| %>
  <div class="row">
    <%= f.input :profile_id, collection: @trailers, label_method: :full_name, value_method: :id, label:false, wrapper_html: {class: 'col s12 m6 l6'}, prompt: 'Select Trailer' %>
    <div class="col s12 m6 l6 margin-top-18-px">
      <%= f.collection_radio_buttons :race_category, [['Senior', 'Senior'] ,['Junior', 'Junior']], :first, :last, { checked: 'Senior' } %>
    </div>
  </div>
  <div class="row">
    <%= f.input :amount, label: 'Amount Paid', wrapper_html: {class: 'col s12 m6 l6'} %>
    <div class="col s12 m6 l6 margin-top-18-px">
      <%= f.collection_radio_buttons :currency, [['MUR', 'MUR'] ,['EUR', 'EUR']], :first, :last, { checked: 'MUR' } %>
    </div>
  </div>
  <div class="row">
    <div class="col s12 m12 l12 margin-top-18-px">
      <%= f.collection_radio_buttons :payment_method, [['Bank Transfer', 'Bank Transfer'] ,['Cash', 'Cash'], ['Cheque' ,'Cheque']], :first, :last %>
    </div>
  </div>
  <div class="row">
    <div class="col s12 m12 l12">
      <%= f.button :submit, "Register" %>
    </div>
  </div>
<% end %>
</div>

app/views/event_registrations/_lookup_form.html.erb
<div id="lookup-form">
  <%= simple_form_for :edit_profile, url: profiles_load_path, remote: true do |f| %>
    <%= f.input :id, collection: @trailers, label_method: :full_name, value_method: :id, label:false, prompt: 'Select Trailer to Edit'  %>
    <%= hidden_field_tag :event_id, @event.id if @event %>
    <%= f.button :submit, "Edit" %>
  <% end %>
</div>

app/views/event_registrations/_participants.html.erb
<table id="participants">
  <thead>
    <tr>
        <th data-field="id">Name</th>
        <th data-field="name">Category</th>
        <th data-field="price">Paid</th>
        <th></th>
    </tr>
  </thead>

  <tbody>
    <%= render @registrations %>
  </tbody>
</table>

app/views/event_registrations/_payment.html.erb
<div id="payment">
  <%= link_to "Confirm Registration", trail_event_event_registrations_path(@event.trail.id, @event.id), method: :post, remote: true, class: "waves-effect waves-light btn" %>
</div>

app/views/event_registrations/create.js.erb
<% if @admin %>
  $('<%= j render(@registration) %>').hide().appendTo('#participants').show(250);
<% else %>
  $('#form-block').replaceWith("<%= j render 'trails/form_block' %>");
  $('.profile-form').closeModal();
  $('.lean-overlay').fadeOut(250, function() {
    $(this).remove();
  });
<% end %>

app/views/event_registrations/destroy.js.erb
$('#<%= dom_id(@registration) %>').fadeOut(250, function() {
  $(this).remove();
});

app/views/event_registrations/new.html.erb
<h2>
  <%= "#{@event.trail.name} #{@event.distance}k" %>
</h2>

<% if current_user.is_admin? %>

  <div class='row'>
    <div class='col s12 m8 l8'>
      <%= render 'form' %>
    </div>

    <div class='col s12 m4 l4'>
      <div class="card-panel">
        <h4>
          Manage Database
        </h4>
        <!-- Modal Trigger -->
        <a class="waves-effect waves-light btn modal-trigger" href="#modal1">Add</a>
        
        <%= render 'lookup_form' %>
      </div>

      <!-- Modals -->
      <div id="modal1" class="modal profile-form">
        <div class="modal-content">
          <%= render 'profiles/form', edit: false, admin: true %>
        </div>
        <%= render 'common/preloader' %>
      </div>
      <div id="modal2" class="modal profile-form">
        <div class="modal-content">
          
        </div>
        <%= render 'common/preloader' %>
      </div>
    </div>
  </div>

  <div class='row'>
    <div class='col s12'>
      <h3>
        Participants
      </h3>
      <%= render 'participants' %>
    </div>
  </div>

<% else %>

  <div class='row'>
    <div class='col s12'>
      <%= render 'payment' %>
    </div>
  </div>
  
<% end %>