config/routes.rb
Rails.application.routes.draw do

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

  get 'dashboard/index'

  scope "/admin" do
    get '/', to: 'dashboard#index'
  end

  scope ':locale', locale: /en|fr/ do
    root 'home#land'
    devise_for :users, :path => 'accounts'
    resources :data
    resources :users
    resources :profiles
    post 'profiles/load', :to => 'profiles#load'

    resources :trails do
      resources :events do
        resources :event_registrations
      end
    end

    resources :posts

    get "/:id" => "high_voltage/pages#show", :as => :page, :format => false
  end
  
end

app/models/trail.rb
# == Schema Information
#
# Table name: trails
#
#  id                   :integer          not null, primary key
#  name                 :string
#  description          :text
#  location             :string
#  date                 :datetime
#  external_link        :string
#  register_online      :boolean
#  organiser            :string
#  course               :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  results_file_name    :string
#  results_content_type :string
#  results_file_size    :integer
#  results_updated_at   :datetime
#

class Trail < ActiveRecord::Base
  has_many :events
  has_attached_file :results,
                    storage: :s3,
                    s3_credentials: Proc.new{|a| a.instance.s3_credentials }

  validates :name, :date, :organiser, :description, presence: true
  validates_attachment_content_type :results, content_type: ['application/pdf']


  def is_finished?
    self.date < DateTime.now
  end

  def results_posted?
    self.results_file_name
  end

  def registration_open?
    self.register_online
  end

  def slug
    name.downcase.gsub(" ", "-")  
  end

  def to_param
    "#{id}-#{slug}"
  end

  def s3_credentials
    {:bucket => ENV['S3_BUCKET_NAME'], :access_key_id => ENV['AWS_ACCESS_KEY_ID'], :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']}
  end
end

app/controllers/trails_controller.rb
# == Schema Information
#
# Table name: trails
#
#  id                   :integer          not null, primary key
#  name                 :string
#  description          :text
#  location             :string
#  date                 :datetime
#  external_link        :string
#  register_online      :boolean
#  organiser            :string
#  course               :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  results_file_name    :string
#  results_content_type :string
#  results_file_size    :integer
#  results_updated_at   :datetime
#

class TrailsController < ApplicationController

  respond_to :html, :js

  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :find_trail, only: [:edit, :update]

  def index
    @trails = Trail.all.order(:date).includes(:events)
    @next_trail ||= Trail.includes(:events).where('date >= ?', DateTime.now).order(date: :asc).first
  end

  def show
    @trail = Trail.includes(:events).find(params[:id])
    @profile = current_user.profile || Profile.new if user_signed_in?
    @participants = Hash.new
    @trail.events.each do |event|
      @participants[event] = event.participants
      if user_signed_in? && current_user.has_profile? && current_user.profile.is_registered?(event)
        @registered_event = event
      end
    end
  end

  def new
    @trail = Trail.new
  end

  def create
    @trail = Trail.new(trail_params)
    if @trail.save
      redirect_to trail_path(@trail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @trail.update_attributes(trail_params)
    @trail.save!
    redirect_to @trail
  end

private
  def find_trail
    @trail = Trail.find(params[:id])
  end

  def trail_params
    params.require(:trail).permit(:name, :date, :location, :organiser, :description, :external_link, :register_online, :results)
  end

end

app/helpers/trails_helper.rb
# == Schema Information
#
# Table name: trails
#
#  id                   :integer          not null, primary key
#  name                 :string
#  description          :text
#  location             :string
#  date                 :datetime
#  external_link        :string
#  register_online      :boolean
#  organiser            :string
#  course               :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  results_file_name    :string
#  results_content_type :string
#  results_file_size    :integer
#  results_updated_at   :datetime
#

module TrailsHelper
  def show_trail_bg
    "background: url('http://get-muddy.com/wp-content/uploads/2014/12/crossingstream1.jpg') no-repeat top center;"
  end

  def in_rodrigues?(location)
    location == "Rodrigues"
  end
end

app/views/trails/_event_details.html.erb
<h2>
  <%= "#{@event.distance}k" %>
</h2>
<p>
  <strong><%= t('trail.start') %></strong> <%= @event.departure %>
<br />
  <strong><%= t('trail.via') %></strong> <%= @event.course %>
<br />
  <strong><%= t('trail.finish') %></strong> <%= @event.arrival %>
</p>

app/views/trails/_form.html.erb
<%= simple_form_for @trail do |f| %>
  <%= f.input :name %>
  <%= f.input :date, as: :string, input_html: {class: "datepicker"} %>
  <%= f.input :location %>
  <%= f.input :organiser %>
  <%= f.input :description, input_html: {class: 'materialize-textarea'} %>
  <%= f.input :external_link %>
  <%= f.input :register_online, label: false, wrapper_html: {class: "switch"} do %>
    <%= f.label :register_online do %>
      <%= f.check_box :register_online %>
      Enable Registration <span class="lever"></span>
    <% end %>
  <% end %>
  <h4>Results</h4>
  <div class="file-field input-field">
    <div class="btn">
      <span>File</span>
      <%= f.file_field :results %>
    </div>
    <div class="file-path-wrapper">
      <input class="file-path validate" type="text">
    </div>
  </div>
  <%= f.button :submit %>
<% end %>

app/views/trails/_form_block.html.erb
<span id="form-block">
  <% if user_signed_in? %>
    <% if @registered_event && !current_user.is_admin? %>
      <h3>
        <%= raw "#{t('register.registered')} #{@registered_event.distance}k" %>
      </h3>
      <% @trail.events.each do |event| %>
        <% @event = event %>
        <%= render "trails/event_details" %>
      <% end %>
    <% else %>
      <% @trail.events.each do |event| %>
        <% @event = event %>
        <%= render "trails/event_details" %>
        <% if current_user.is_admin? %>
          <p>
            <%= link_to "Manage Registration", new_trail_event_event_registration_path(event.trail, event), class: "waves-effect waves-light btn" %>
          </p>
        <% else %>
          <% if @registered_event && !current_user.is_admin? %>
            <%= raw "<strong>#{t('register.registered')} #{@registered_event.distance}k</strong>" %>
          <% else %>
            <p>
              <a class="waves-effect waves-light btn modal-trigger" href=<%= "#profile-form-modal-#{event.id}" %> >
                <%= "#{t('register.for')} #{event.distance}k" %>
              </a>
            </p>
            <!-- Modals -->
            <div id=<%= "profile-form-modal-#{event.id}" %> class="modal profile-form outside-dashboard do-not-animate">
              <div class="modal-content">
                <% if current_user.has_profile? %>
                  <%= render 'profiles/form', edit: true, admin: false %>
                <% else %>
                  <%= render 'profiles/form', edit: false, admin: false %>
                <% end %>
                <%= render 'common/preloader' %>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% else %>
    <% @trail.events.each do |event| %>
      <% @event = event %>
      <%= render "trails/event_details" %>
    <% end %>
    <p>
      <a class="waves-effect waves-light btn modal-trigger" href="#login-form-modal">
        <%= t('register.login') %>
      </a>
    </p>
    <p>
      Don't have a login?
      <%= link_to "Click here to sign up.", new_registration_path(resource_name) %>
    </p>
    <!-- Modals -->
    <div id="login-form-modal" class="modal login-form outside-dashboard do-not-animate">
      <div class="modal-content">
        <%= render 'devise/sessions/new' %>
      </div>
    </div>
  <% end %>
</span>

app/views/trails/_participants.html.erb
<div class="tile tile-lg tile-full-width tile-flexible-height tile-light-blue">
  <span class="content-wrapper">
    <span class="tile-content">
      <h2>
        Participants
      </h2>
      <% @trail.events.each do |event| %>
      <span class="left-col">
        <h3>
          <%= "#{event.distance}k" %>
          <% if user_signed_in? && current_user.is_admin? %>
            <%= link_to raw("<i class='material-icons'>file_download</i>"), trail_event_event_registrations_path(@trail, event), class: 'btn-floating btn-large waves-effect waves-light tooltipped',  data: { position: "right", delay: "50", tooltip: "Download" } %>
          <% end %>
        </h3>
        <h5>
          <%= pluralize(@participants[event].count, 'participant') if @participants[event].length > 0 %>
        </h5>
        <ul>
          <% @participants[event].each do |participant| %>
            <li>
              <%= participant.full_name %>
            </li>
          <% end %>
        </ul>
      </span>
      <% end %>
    </span>      
  </span>
</div>

app/views/trails/_register.html.erb
<div id="register" class="tile tile-lg tile-green">
  <span class="content-wrapper">
    <span class="tile-content">
      <%= render 'form_block' %>
    </span>      
  </span>
</div>

app/views/trails/_results.html.erb
<div id="results" class="tile tile-lg tile-green">
  <span class="content-wrapper">
    <span class="tile-content">
      <h3 class="next-trail-name">
        <%= t('results.title') %>
      </h3>
      <p>
        <% if @trail.results_posted? %>
          <%= link_to raw("Open <i class='material-icons'>open_in_new</i>"), @trail.results.url, class: 'waves-effect waves-light btn', target: '_blank' %>
        <% else %>
          <%= t('results.pending') %>
        <% end %>
      </p>
      <% if user_signed_in? && current_user.is_admin? %>
        <h4>Upload Results</h4>

        <%= form_for @trail, html: { multipart: true } do |f| %>
          <div class="file-field input-field">
            <div class="btn">
              <span>File</span>
              <%= f.file_field :results %>
            </div>
            <div class="file-path-wrapper">
              <input class="file-path validate" type="text">
            </div>
          </div>
          <%= f.submit "Upload", class: 'btn' %>
        <% end %>

      <% end %>  
    </span>      
  </span>
</div>

app/views/trails/_trail.html.erb
<%= link_to url_with_protocol(trail.external_link) || trail_path(trail),  class: ["tile tile-short tile-narrow ripple-effect", (in_rodrigues?(trail.location) ? "tile-deep-orange" : "tile-deep-orange-inverse")], target: ("_blank" if trail.external_link.present?) do %>
  <span class="content-wrapper">
    <span class="tile-content">
      <h4 class="trail-date">
        <%= l trail.date, format: '%-d %B %Y' if trail.date %>
      </h4>
      <h2>
        <%= trail.name %>
      </h2>
      <h4>
        <% trail.events.each do |event| %>
          <%= "#{event.distance}k" %>
        <% end %>
      </h4>
      <p>
        <%= trail.description %>
      </p>
      
      <% if in_rodrigues?(trail.location) %>
        <h4>
          <%= t('trail_league.title') %>
        </h4>
      <% end %>

      <p class="tile-footer">
        <span class="btn-floating btn-large waves-effect waves-light orange">
          <i class='material-icons'>arrow_forward</i>
        </span>
        
      </p>
    </span>      
  </span>
<% end %>

app/views/trails/edit.html.erb
<div class="row">
  <div class="col s12 l6 offset-l3">
    <h2>
      Edit <%= @trail.name %>
    </h2>
    <%= render 'form' %>
  </div>
</div>

app/views/trails/index.html.erb
<div class="tile tile-short tile-narrow tile-green">
  <span class="content-wrapper">
    <span class="tile-content">
      <h1>
        Rodrigues
        <%= t('trail_league.calendar') %>
        <% if user_signed_in? && current_user.is_admin? %>
          <%= link_to raw("<i class='material-icons'>add</i>"), new_trail_path, class: 'btn-floating btn-large waves-effect waves-light tooltipped',  data: { position: "right", delay: "50", tooltip: "Create New Trail" } %>
        <% end %>
      </h1>
      <h2>
        Contacts
      </h2>
      <ul>
        <li>
          <i class='material-icons'>phone</i><strong> Louis Henrico</strong> 5877 0007
        </li>
        <li>
          <i class='material-icons'>phone</i><strong> Patrice Chan Seem</strong> 5722 3777
        </li>
      </ul>
    </span>      
  </span>
</div>

<div class="tile tile-short tile-narrow tile-green">
  <span class="content-wrapper">
    <span class="tile-content">
      <span class="tile-img tile-img-bg load-first jumping-off-sq"></span>
    </span>      
  </span>
</div>

<div class="tile tile-short tile-narrow tile-light-blue ripple-effect">

  <span class="content-wrapper">
    <span class="tile-content">
      <h2>
        <%= t('trail_league.next_trail') %>
      </h2>
      <% if @next_trail %>
        <h4>
          <%= l @next_trail.date, format: '%-d %B %Y' if @next_trail.date %>
        </h4>
        <h2>
          <%= link_to @next_trail.name, trail_path(@next_trail) %>
        </h2>
        <h4>
          <% @next_trail.events.each do |event| %>
            <%= "#{event.distance}k" %>
          <% end %>
        </h4>
        <p class="tile-footer">
          <%= link_to raw("<i class='material-icons'>arrow_forward</i>"), trail_path(@next_trail), class: "btn-floating btn-large waves-effect waves-light blue lighten-2" %>
        </p>
      <% end %>
    </span>      
  </span>
</div>
<%= render @trails %>

app/views/trails/new.html.erb
<div class="row">
  <div class="col s12 l6 offset-l3">
    <h2>
      Create New Trail
    </h2>
    <%= simple_form_for @trail do |f| %>
      <%= f.input :name %>
      <%= f.input :date, as: :string, input_html: {class: "datepicker"} %>
      <%= f.input :location %>
      <%= f.input :organiser %>
      <%= f.input :description, input_html: {class: 'materialize-textarea'} %>
      <%= f.input :external_link %>
      <%= f.input :register_online, label: false, wrapper_html: {class: "switch"} do %>
        <%= f.label :register_online do %>
          <%= f.check_box :register_online %>
          Enable Registration <span class="lever"></span>
        <% end %>
      <% end %>
      <%= f.button :submit, "Create Trail and Add Event Distances" %>
    <% end %>
  </div>
</div>

app/views/trails/show.html.erb
<a class="tile tile-lg tile-pink ripple-effect" href="#">
  <span class="content-wrapper">
    <span class="tile-content">
      
      <span class="tile-img tile-img-bg load-first runners-through-trees"></span>
      <span class="tile-holder tile-holder-sm">
        <span class="title"><%= @trail.name %></span>
      </span>
    </span>      
  </span>
</a>

<div class="tile tile-lg tile-narrow tile-deep-orange">
  <span class="content-wrapper">
    <span class="tile-content">
      <h4 class="trail-date">
        <%= l @trail.date, format: '%-d %B %Y' if @trail.date %>
      </h4>
      <h2>
        <%= @trail.name %>
        <% if user_signed_in? && current_user.is_admin? %>
            <%= link_to raw("<i class='material-icons'>edit</i>"), edit_trail_path(@trail), class: 'btn-floating btn-large waves-effect waves-light tooltipped',  data: { position: "top", delay: "50", tooltip: "Edit #{@trail.name}" } %>
        <% end %>
      </h2>
      <p>
        <%= @trail.description %>
      </p>
      <h4>
        Courses: 
        <% @trail.events.each do |event| %>
          <%= "#{event.distance}k" %>
          <% if user_signed_in? && current_user.is_admin? %>
              <%= link_to raw("<i class='material-icons'>edit</i>"), edit_trail_event_path(@trail, event), class: 'btn-floating btn-large waves-effect waves-light tooltipped',  data: { position: "bottom", delay: "50", tooltip: "Edit #{event.distance}k" } %>
          <% end %>
        <% end %>
        <% if user_signed_in? && current_user.is_admin? %>
            <%= link_to raw("<i class='material-icons'>add</i>"), new_trail_event_path(@trail), class: 'btn-floating btn-large waves-effect waves-light tooltipped',  data: { position: "bottom", delay: "50", tooltip: "Add Course" } %>
        <% end %>  
      </h4>
      
      <p>
        <%= t('trail.organiser') %>:
        <%= @trail.organiser %>
      </p>
      <% if in_rodrigues?(@trail.location) %>
        <h4>
          <%= t('trail_league.title') %>
        </h4>
      <% end %>
      <p>
        <%= t('register.adults') %>: Rs150, <%= t('register.children') %>: Rs100
      </p>
    </span>      
  </span>
</div>

<div class="tile tile-lg tile-narrow tile-light-blue">
  <span class="content-wrapper">
    <span class="tile-content">
      
      <span class="tile-img tile-img-bg load-first jumping-off-sq"></span>
      
    </span>      
  </span>
</div>

<%= render @trail.is_finished? ? 'results' : 'register' %>

<%= render 'participants' %>